FROM docker.elastic.co/kibana/kibana:7.14.0
COPY kibana/kibana.yml /usr/share/kibana/config/kibana.yml
COPY security/elasticsearch-ssl-http/kibana/elasticsearch-ca.pem /usr/share/kibana/config/elasticsearch-ca.pem
